;;
;; init-requires.el in ramnes/.emacs.d/lisp
;; <contact@ramnes.eu>
;;

(require 'ac-ispell)
(require 'android-mode)
(require 'async)
(require 'auto-complete)
(require 'auto-complete-config)
(require 'autopair)
(require 'column-enforce-mode)
(require 'dash)
(require 'dockerfile-mode)
(require 'ediff)
(require 'editorconfig-core)
(require 'editorconfig)
(require 'flymake)
(require 'flymake-go)
(require 'flymake-diagnostic-at-point)
(require 'flymake-shellcheck)
(require 'git-gutter)
(require 'git-messenger)
(require 'go-autocomplete)
(require 'go-mode-autoloads)
(require 'hcl-mode)
(require 'helm)
(require 'helm-swoop)
(require 'htmlize)
(require 'jedi)
(require 'jinja2-mode)
(require 'json-reformat)
(require 'lua-mode)
(require 'magit)
(require 'markdown-mode)
(require 'mmm-auto)
(require 'move-border)
(require 'multiple-cursors)
(require 'nginx-mode)
;; (require 'php-mode)
(require 'pip-requirements)
(require 'popup)
(require 'popwin)
(require 'python-black)
(require 'rainbow-delimiters)
(require 'rst)
(require 'rust-mode)
(require 'saveplace)
(require 'smerge-mode)
(require 'terraform-mode)
(require 'transpose-frame)
(require 'typescript)
(require 'web-mode)
(require 'wikitext-mode)
(require 'yaml-mode)
