;;
;; init-requires.el in ramnes/.emacs.d/lisp
;; <contact@ramnes.eu>
;;

(require 'android-mode)
(require 'ac-ispell)
(require 'auto-complete)
(require 'auto-complete-config)
(require 'autopair)
(require 'column-enforce-mode)
(require 'git-commit)
(require 'go-mode-autoloads)
(require 'flymake)
(require 'flymake-cursor)
(require 'helm)
(require 'helm-swoop)
(require 'hlinum)
(require 'htmlize)
(require 'jedi)
(require 'jinja2-mode)
(require 'lua-mode)
(require 'markdown-mode)
(require 'move-border)
(require 'mmm-auto)
(require 'multiple-cursors)
;; (require 'php-mode)
(require 'popup)
(require 'rst)
(require 'rainbow-delimiters)
(require 'rust-mode)
(require 'saveplace)
(require 'web-mode)
(require 'wikitext-mode)
(require 'yaml-mode)
